dist: xenial
language: node_js
node_js:
  - "12.11.1"
script:
  - yarn run test
before_install:
  - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - yarn run coveralls
